//
//  DetailPresenter.swift
//  pHNews
//
//  Created by Phanvit Chevamongkolnimit on 5/9/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic
{
    func presentWebUrl(response: Detail.WebUrl.Response)
}

class DetailPresenter: DetailPresentationLogic
{
    weak var viewController: DetailDisplayLogic?
    
    // MARK: Do something
    
    func presentWebUrl(response: Detail.WebUrl.Response)
    {
        if let urlString = response.url {
            let url = URL(string: urlString)
            let viewModel = Detail.WebUrl.ViewModel(url: url)
            viewController?.displayNews(viewModel: viewModel)
        }
        
    }
}
