//
//  MainInteractor.swift
//  pHNews
//
//  Created by Phanvit Chevamongkolnimit on 18/8/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic
{
    func requestNewsEverything(request: Main.News.Request.Everything)
    func requestNewsTopHeadline(request: Main.News.Request.TopHeadline)
}

protocol MainDataStore
{
    var newsArticle: [NewsArticle] { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore
{
    var presenter: MainPresentationLogic?
    var worker: MainWorker?
    var newsArticle:[NewsArticle] = []
    // MARK: Do something
    
    func requestNewsEverything(request: Main.News.Request.Everything)
    {
        worker = MainWorker()
        worker?.requestNewsEverything(request: request, completionHandler: {[weak self] response in
            self?.presenter?.presentNews(response: Main.News.Response(article: response?.articles))
        }, errorHandler: {[weak self] error in
            self?.presenter?.presentNews(response: Main.News.Response(article: nil, error: error))
        })
    }
    
    func requestNewsTopHeadline(request: Main.News.Request.TopHeadline) {
        worker = MainWorker()
        worker?.requestNewsTopHeadline(request: request, completionHandler: {[weak self] response in
            self?.presenter?.presentNews(response: Main.News.Response(article: response?.articles))
        }, errorHandler: {[weak self] error in
            self?.presenter?.presentNews(response: Main.News.Response(article: nil, error: error))
        })
    }
}
