//
//  MainPresenter.swift
//  pHNews
//
//  Created by Phanvit Chevamongkolnimit on 18/8/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic
{
    func presentNews(response: Main.News.Response)
}

class MainPresenter: MainPresentationLogic
{
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    
    func presentNews(response: Main.News.Response) {
        if (response.error != nil) {
            self.viewController?.displayNews(viewModel: Main.News.ViewModel(error:response.error))
        } else {
            
            let article = response.article?.filter {($0.title != nil || $0.title != "[Removed]") && $0.urlToImage != nil && $0.description != nil && $0.url != nil }
            
            let vm = article?.compactMap({ article in
                return NewsArticle(title: article.title, description: article.description, urlImage: article.urlToImage, url: article.url)
            })
            self.viewController?.displayNews(viewModel: Main.News.ViewModel(listNews: vm))
        }
    }
}
