//
//  MainWorker.swift
//  pHNews
//
//  Created by Phanvit Chevamongkolnimit on 18/8/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class MainWorker
{
    func requestNewsEverything(request: Main.News.Request.Everything, completionHandler: @escaping (NewsResponseModel?) -> Void, errorHandler: @escaping (any Error) -> Void) {
        NewsAPI().requestAPI(.everything(request.everything)) { (response:NewsResponseModel?) in
            completionHandler(response)
        } errorHandler: { error in
            errorHandler(error)
        }
    }
    
    func requestNewsTopHeadline(request: Main.News.Request.TopHeadline, completionHandler: @escaping (NewsResponseModel?) -> Void, errorHandler: @escaping (any Error) -> Void) {
        
        NewsAPI().requestAPI(.topHeadline(request.topHeadline)) { (response:NewsResponseModel?) in
            completionHandler(response)
        } errorHandler: { error in
            errorHandler(error)
        }
    }
}
