//
//  MainModels.swift
//  pHNews
//
//  Created by Phanvit Chevamongkolnimit on 18/8/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main
{
    // MARK: Use cases
    
    enum News
    {
        struct Request
        {
            struct Everything {
                var everything: EverythingRequest
            }
            struct TopHeadline {
                var topHeadline: TopHeadlineRequest
            }
        }
        
        struct Response
        {
            var article:[Article]?
            var error:Error?
        }
        struct ViewModel
        {
            var listNews:[NewsArticle]?
            var error:Error?
        }
    }
}

struct NewsArticle {
    let title: String?
    let description: String?
    let urlImage: String?
    let url: String?
}
